gophermart
msmkdenis/yap-gophermart pull request #1
Opened 2023-12-04 08:04 UTC by msmkdenis

2023-12-26 14:57 UTC, rktkov requested changes

2023-12-26 14:57 UTC, rktkov commented on internal/utils/jwt_manager.go
> +	logger    *zap.Logger
Я бы для логгирования сделал бы внутренний пакет, с необходимым интерфейсом, а внутри пакета уже использовал бы библиотеку. Так будет больше гибкости в ситуации, если захочется расширить инструменты логгирования.

2023-12-26 14:57 UTC, rktkov commented on internal/user/userrepository/user_repository.go
> +	PostgresPool *db.PostgresPool
А точно нам нужно поле делать открытым/доступным вне структуры.

2023-12-26 14:57 UTC, rktkov commented on internal/user/userhandler/user_handler.go
> +package userhandler
Я бы пакеты переименовал, убрав слово user. Так и дерево проекта будет чище и лишнее повторяющееся слово уйдет. И тоже самое для пакетов других сущностей сделал бы.

2023-12-26 14:57 UTC, rktkov commented on internal/order/orderservice/order_accrual_service.go
> +	if err == nil {
Более привычно, когда первым рассматривают случай когда ошибка не nil. А потом уже идет код в основном теле функции в ситуации, когда ошибки нет. Стоит перенести код с 88 строчки сюда.

2023-12-26 14:57 UTC, rktkov commented on internal/order/orderservice/order_accrual_service.go
> +		errUpdateBalance := oc.balanceRepository.UpdateBalance(context.Background(), o.UserLogin, o.Accrual)
Я точно хочу делать обновление баланса, если у меня выше произошла ошибка обновления заказа? Очень похоже, что могу консистентность данных порушить.
Тут вообще подумать, как два действия объединить в одно контролируемое. Т.е. если хотя бы в одном запросе, что пойдет не так, откатить уже выполненные действия.

2023-12-26 14:57 UTC, rktkov commented on internal/order/orderservice/order_service.go
> +	"github.com/msmkdenis/yap-gophermart/internal/apperrors"
Это осознанное обособление инициализации пакета ошибок отдельно от других внутренних пакетов?

2023-12-26 14:57 UTC, rktkov commented on internal/middleware/request-logger.go
> +	// берём структуру для хранения сведений об ответе
В других местах кода я видел комментарии на английском языке. Надо выбрать один язык и использовать его во всем коде.

2023-12-26 14:57 UTC, rktkov commented on internal/app/gophermart/app.go
> +	quit := make(chan os.Signal, 1)
Я бы обработку сигналов о завершении процесса из ОС вынес бы в main.

2023-12-26 14:57 UTC, rktkov commented on internal/app/gophermart/app.go
> +		// Shutdown signal with grace period of 30 seconds
Вот комментарий на английском.

2023-12-27 11:31 UTC, msmkdenis commented on internal/user/userrepository/user_repository.go
> +	PostgresPool *db.PostgresPool
Скорректировал здесь и в других пакетах для аналогичных случаев

2023-12-27 11:31 UTC, msmkdenis commented on internal/user/userhandler/user_handler.go
> +package userhandler
Скорректировал

2023-12-27 11:33 UTC, msmkdenis commented on internal/order/orderservice/order_accrual_service.go
> +	if err == nil {
Скорректировал

2023-12-27 12:51 UTC, msmkdenis commented on internal/order/orderservice/order_service.go
> +	"github.com/msmkdenis/yap-gophermart/internal/apperrors"
Скорректировал, так не должно было быть

2023-12-27 12:52 UTC, msmkdenis commented on internal/order/orderservice/order_accrual_service.go
> +		errUpdateBalance := oc.balanceRepository.UpdateBalance(context.Background(), o.UserLogin, o.Accrual)
Вынес логику взаимодействия с accrual системой в отдельный пакет.
Обновление и order  и balance сделал в рамках одной транзакции.

2023-12-27 12:54 UTC, msmkdenis commented on internal/middleware/request-logger.go
> +	// берём структуру для хранения сведений об ответе
Убрал англоязычные комментарии

2023-12-27 12:54 UTC, msmkdenis commented on internal/app/gophermart/app.go
> +		// Shutdown signal with grace period of 30 seconds
Убрал

2023-12-30 19:50 UTC, msmkdenis commented on internal/order/orderservice/order_accrual_service.go
> +		errUpdateBalance := oc.balanceRepository.UpdateBalance(context.Background(), o.UserLogin, o.Accrual)
Решил изменить подход. В описанном выше бизнес логика "протекала" в слой репозитория. При этом чтобы не запускать транзакции в сервисе приходилось делать отдельный репозиторий, который вызывал методы более подходящие другим доменам. 
Добавил transaction manager для управления транзакциями из слоя сервиса. Убрал "лишний репозиторий". В transaction manager запускаю методы из разных репозиториев (в данном случае из order и balance репозиториев).

2024-01-09 13:36 UTC, msmkdenis commented
Поправил основные проблемные места + нашел у себя некорректную обработку ошибки constraint-а из ДБ: ошибка при некорректном withdrawal показывалась как ошибка отрицательного баланса. 
Сделал отдельную проверку на именованный constraint, сделал валидацию на положительную сумму списания в хендлере (в базу больше не пускает).

2024-01-12 08:04 UTC, msmkdenis commented on internal/utils/jwt_manager.go
> +	logger    *zap.Logger
Понимаю причину - позволит нам в одном месте поменять логгер на любой другой, не меня код в дальнейшем в теле проекта, т.к. он будет завязан на внутренние интерфейсы. Если возможно оставил бы пока такую реализацию.

2024-01-12 08:20 UTC, msmkdenis commented on internal/app/gophermart/app.go
> +	quit := make(chan os.Signal, 1)
канал с ос сигналами вынес в main, передаю его в run и там обрабатываю

2024-01-12 19:55 UTC, rktkov approved these changes

2024-01-14 12:35 UTC, merged